### PR TITLE
Add Idaho Falls file

### PR DESCRIPTION
**Pull request by harterj**
This is the beginning of the Idaho Falls file 💯 

I'll take any feedback on 
- other attractions, if you've been here
- what kind of restaurants are here? ✌️ 
- I know @albeanth @doubwoods3  think Idaho Falls  is pretty fun...

### CODE REVIEW

**Comment by skamphax0r** [comment]
never been there - :beers:

**Comment by skamphax0r** [comment]
:shipit: !

**Comment by albeanth** [comment]
:shipit: 

...I guess.... 😄

**Comment by harterj** [comment]
@doubwoods3 that is true, I forgot you haven't been here. Anyway, I added some restaurant destinations if you DO visit. 71e6e387b4c08d02304218bf342d9e3fc7a9543a

**Comment by harterj** [comment]
:shipit:

**Comment by doubwoods3** [comment]
> that is true, I forgot you haven't been here. Anyway, I added some restaurant destinations if you DO visit. 71e6e38

roger that!

🚀 🚢 :shipit:

**Pull request merged**
