### PR TITLE
Monterrey file (Edd-mty.md)

### PR DESCRIPTION
**Pull request by EddLeon**
This is the beginning of the mty file  :scorpius: 

Pls provide feedbackus :

- If you have been to Mexico
 - Monterrey to be especific
- @nysertxs @aang7  @shinton @medianick  @shahchirag1  @amypiazza00 @benisntfunny @beardofedu Do you like tacos?
- Have you been to any of the attractions listed on the file
- @beardofedu Do you love tequila :beer:  :beers:

### CODE REVIEW

**Comment by nysertxs** [comment]
> Do you like tacos?

i love them 😍

**Comment by aang7** [comment]
:baby:  nigga nigga

**Comment by EddLeon** [comment]
> Do you like tacos?

@nysertxs  tanks for the info

**Comment by syapsic** [comment]
🚢

**Comment by nysertxs** [comment]
👍

**Pull request merged**
