### PR TITLE
Add benisntfunny-chicago.md file

### PR DESCRIPTION
**Pull request by benisntfunny**
Please review the amazing attractions I've added that will really make this project **boss** 😎 .

Please send all complaints to @githubteacher 👍 
Complaints can include:
- Dislike of the mark down used
- Hate the attractions mentioned
- Don't like chicago in general

### CODE REVIEW

**Comment by banderso2** [comment]
Why don't you like Chicago?

**Comment by benisntfunny** [comment]
I do like Chicago?

**Comment by banderso2** [comment]
Looks great :ship:

**Comment by benisntfunny** [comment]
I'M SHIPPING 7d59f59. Toot toot!

**Comment by yashkmankad** [comment]
:shipit:

**Pull request merged**
