### PR TITLE
Add Nashua file

### PR DESCRIPTION
**Pull request by yashkmankad**
Initial draft of Nashua file :city_sunset: 

Please provide feedback on:

- if you've been to Nashua, or the New England Area, what did you like ? what did you not like ? :football: 
- If you do plan to visit, come during the Fall, it is the best place in the country to see the Fall colors! :fallen_leaf: 
- @githubteacher testing the @mention feature :smiley:

### CODE REVIEW

**Comment by yashkmankad** [comment]
@vibin22 , @manpreet07 -- I see you guys are from Boston, have you ever been to Nashua ?
Also, just testing out the conversation feature! :smile:

**Comment by yashkmankad** [comment]
Added restaurants and remote attractions in 81f9de4

**Comment by benisntfunny** [comment]
:shipit: 👍

**Comment by yashkmankad** [comment]
Thank you @benisntfunny

**Pull request merged**
