### PR TITLE
add milwaukee file

### PR DESCRIPTION
**Pull request by skamphax0r**
#52 step 3 - attractions in milwaukee  :hankey: 

please provide feedback on:

- if you have been there, what did you like/not like? 
- if you haven't been to Milwaukee, why would you? 
- other stuff
- @piyushsandhir - what did you think of the area? :question: 
- @beardofedu - have you been to MKE?

### CODE REVIEW

**Comment by sdcalmes** [comment]
Brewery tours. Especially Lakefront

**Comment by skamphax0r** [comment]
@sdcalmes - awaiting your :+1:

**Comment by sdcalmes** [comment]
:shipit: :+1:

**Comment by beardofedu** [comment]
@skamphax0r I have not been to MKE :'(, I do love the Alice Cooper scene from Wayne's World though 😄 
Don't forget to assign yourself 😀

**Pull request merged**
