### PR TITLE
Add Orlando file

### PR DESCRIPTION
**Pull request by githubteacher**
This is the beginning of the Orlando file ☀️ 

Please provide feedback on:

- if you've been to Orlando, what did you like? what did you not like?
- if you've never been to Orlando, what interests you about coming here?
- are you interested in learning about lodging? What do you prefer? Hotels? AirBNBs? etc
- @crichid what kinds of things would your son like to do?
- @beardofedu do you know of any good 🍻 breweries 🍻  in or around Orlando?

### CODE REVIEW

**Comment by beardofedu** [comment]
@githubteacher Not to familiar with breweries in Orlando, but I enjoy:
- Frank N Steins for some 🍺  and 🎲  
- Player 1 for 🍺 and 🎮 👾

**Comment by githubteacher** [comment]
> Frank N Steins for some 🍺 and 🎲
> Player 1 for 🍺 and 🎮 👾

@beardofedu yes! I've been to both -- will definitely add them to my file!

**Comment by mannu9898** [comment]
- Mumbai for :tada: 
- Delhi-India for :palm_tree:

**Comment by githubteacher** [comment]
@beardofedu I added your suggestions 945ca28

**Comment by ktstevenson** [comment]
Looks good. :shipit:

**Comment by Cohen611** [comment]
:shipit:

**Comment by sathya-ghub** [comment]
@githubteacher Looks good to :ship: !

**Comment by mleacct** [comment]
:+1:

**Comment by skamphax0r** [comment]
:hankey: :shipit:

**Pull request merged**
