### PR TITLE
Adding an entry for Cape Town

### PR DESCRIPTION
**Pull request by SmilyBorg**
I'm adding things for Cape Town. Does anyone know the big one?

### CODE REVIEW

**Comment by yashkmankad** [comment]
Table Mountain ? :mount_fuji:

**Comment by githubteacher** [comment]
@SmilyBorg I'd ❤️  to visit Cape Town -- what are some good things to do there?

**Comment by SmilyBorg** [comment]
Yup Table mountain is the big one
We also have the Silicon cape initiative. Nice start up culture.

**Comment by SmilyBorg** [comment]
Table mountain is worth a visit.
The kistenbosch gardens is a great visit and of course our Wine Route

**Comment by KimThomp** [comment]
@SmilyBorg I :heart: Capetown.  Was there in Feb.  Had great food an simply loved the beach.

**Comment by SmilyBorg** [comment]
I goofed and tried to merge master into my branch

**Pull request closed without merging**
