### PR TITLE
Add San Francisco file

### PR DESCRIPTION
**Pull request by syapsic**
👍

### CODE REVIEW

**Comment by sdcalmes** [comment]
@syapsic 

Instead of adding a new file pertaining to your city, you seemed to have modified the README file. That's not quite what we are trying to do here!

@beardofedu want to help out here?

**Comment by syapsic** [comment]
OK I missed that part. Undid changes to README and added new file. Is this better?

**Comment by sdcalmes** [comment]
The changes to the README seem to still be there. If you click the "Files Changed" button towards the top, you can see that!

But you're on the right path :wink:

**Comment by syapsic** [comment]
Right, so how do I remove unwanted commits from my pull request now?

**Comment by sdcalmes** [comment]
That's a great question and I do not have an answer for you :frowning:

**Pull request merged**
